### ISSUE TITLE
#question

### ISSUE THREAD

**Issue by bokunodev** [egodasa/belajar-golang-2#1]
adakah alasan tertentu anda menggunakan gorila mux sebagai routermux nya ?

**Comment by egodasa** [comment]
@bokunodev Karena Saya masih dalam tahap belajar, Saya belum bisa menyebutkan alasannya secara teknis. 
Saya masih mencoba library lainnya dan tidak sebatas pada router saja. Melainkan Saya masih mempelajari library apa saja yang Saya temukan diinternet.
Pada echo framework, Saya pasti menggunakan router dari bawaan echo framework.
